crimes = [
    {
        "_id": "5bdbba8fed396daf6e72d1d9",
        "address_1": "RANDOLPH ST N & CHURCH ST",
        "city": "URBANA",
        "day_of_week": "Monday",
        "hour_of_day": 23,
        "incident_datetime": "11/01/2018, 21:43:35",
        "incident_description": "WARRANT-IN STATE <BR/><BR/>OFFICER CONDUCTED A TRAFFIC STOP FOR FAILURE TO SIGNAL. A PA SSENGER WAS ARRESTED ON A VALID CHAMPAIGN COUNTY WARRANT. DR IVER WAS RELEASED WITH A WRITTEN WARNING.",
        "incident_id": "882600354",
        "incident_type_primary": "[UIPD] WARRANT-IN STATE",
        "latitude": 40.1183,
        "longitude": -88.2452,
        "parent_incident_type": "Other",
        "state": "IL",
    },
    {
        "_id": "5bdbba8fed396daf6e72d1de",
        "address_1": "800 Block WRIGHT ST S",
        "city": "URBANA",
        "day_of_week": "Thursday",
        "hour_of_day": 20,
        "incident_datetime": "11/01/2018, 21:43:35",
        "incident_description": "THEFT-RETAIL <BR/><BR/>RETAIL THEFT OCCURRED AT IUB. THE SUSPECT WAS APPREHENDED AND THE PROPERTY RETURNED.",
        "incident_id": "883832978",
        "incident_type_primary": "[UIPD] THEFT-RETAIL",
        "latitude": 40.1083,
        "longitude": -88.2292,
        "parent_incident_type": "Theft",
        "state": "IL",
    },
    {
        "_id": "5bdbba8fed396daf6e72d1df",
        "address_1": "1000 Block GREGORY DR E",
        "city": "URBANA",
        "day_of_week": "Thursday",
        "hour_of_day": 23,
        "incident_datetime": "11/01/2018, 21:43:35",
        "incident_description": "OTHER TROUBLE/INFO RPT <BR/><BR/>RESIDENT OF ALLEN HALL DISPOSED OF HOT INCENSE IN GARBAGE CAN. GARBAGE STARTED TO BURN RESULTING IN FIRE ALARM.",
        "incident_id": "883832977",
        "incident_type_primary": "[UIPD] OTHER TROUBLE/INFO RPT",
        "latitude": 40.1041,
        "longitude": -88.221,
        "parent_incident_type": "Other",
        "state": "IL",
    },
]


def get_crimes():
    return crimes
